### ISSUE TITLE
Camera zoom is hard to use.

### ISSUE THREAD

**Issue by schelv** [inaturalist/react-native-inat-camera#44]
**Describe the bug**
Camera zoom is hard to use. It's either no zoom or full zoom.
Zoom level jumps too much even with the smallest touch. 

**To Reproduce**
1. Go to camera
2. Try to zoom a little

**Expected behavior**
That it is easy to zoom a little while using the camera.

**Smartphone:**
 - Device: oneplus nord
 - OS: Android 
 - I'm using the seek beta version

**Comment by schelv** [comment]
I think the label should be 'bug' instead of 'enhancement'

**Comment by jtklein** [comment]
We are in the process of migrating the camera component to use https://github.com/mrousavy/react-native-vision-camera instead of https://github.com/inaturalist/react-native-inat-camera
The zoom would then use native drivers and closely resemble the native camera app at first, so I believe this would no longer be an issue then. Closing it off here.
